version: '3.8'

services:
  app:
    build: .
    container_name: memory_matrix_web
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - web
    labels:
      caddy: memoryMatrix.hackerwerkstatt.de
      caddy.reverse_proxy: "{{upstreams 80}}"
    environment:
      - PORT=80
      - ADMIN_PASSWORD=admin123
    restart: unless-stopped

networks:
  web:
    external: true
